### ISSUE TITLE
Using built-in user model

### ISSUE THREAD

**Issue by Andre197789xh** [guardly/loopback-connector-couchbase#2]
Hi, 

i try to use the connector with the built-in user model. This works fine (also for other, non built-in models) as long as i do not attach the ACL-model to the couchbase datasource. If i do, i get this error in the explorer console (even when doing requests to other, non built-in models):

{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "inq is an unknown key",
    "statusCode": 500,
    "stack": "Error: inq is an unknown key\n    at defaultHandler (C:\Users\Andre\WebstormProjects\couchbase-neu\node_modules\loopback\node_modules\strong-remoting\lib\rest-adapter.js:337:15)\n    at restErrorHandler (C:\Users\Andre\WebstormProjects\couchbase-neu\node_modules\loopback\node_modules\strong-remoting\lib\rest-adapter.js:327:14)\n    at Layer.handle_error (C:\Users\Andre\WebstormProjects\couchbase-neu\node_modules\loopback\node_modules\express\lib\router\layer.js:58:5)\n    at trim_prefix (C:\Users\Andre\WebstormProjects\couchbase-neu\node_modules\loopback\node_modules\express\lib\router\index.js:269:13)\n    at C:\Users\Andre\WebstormProjects\couchbase-neu\node_modules\loopback\node_modules\express\lib\router\index.js:238:9\n    at Function.proto.process_params (C:\Users\Andre\WebstormProjects\couchbase-neu\node_modules\loopback\node_modules\express\lib\router\index.js:313:12)\n    at C:\Users\Andre\WebstormProjects\couchbase-neu\node_modules\loopback\node_modules\express\lib\router\index.js:229:12\n    at Function.match_layer (C:\Users\Andre\WebstormProjects\couchbase-neu\node_modules\loopback\node_modules\express\lib\router\index.js:296:3)\n    at next (C:\Users\Andre\WebstormProjects\couchbase-neu\node_modules\loopback\node_modules\express\lib\router\index.js:190:10)\n    at Layer.handle_error (C:\Users\Andre\WebstormProjects\couchbase-neu\node_modules\loopback\node_modules\express\lib\router\layer.js:54:12)"
  }
}

This is my setup for datasources.json and model-config.json:

{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "couchbase": {
    "connector": "couchbase",
    "database": "user_bucket"
  }
}

{
  ...
  "User": {
    "dataSource": "couchbase",
    "public": true
  },
  "AccessToken": {
    "dataSource": "couchbase",
    "public": true
  },
  "ACL": {
    "dataSource": "couchbase",
    "public": true
  },
  "RoleMapping": {
    "dataSource": "couchbase",
    "public": true
  },
  "Role": {
    "dataSource": "couchbase",
    "public": true
  },
  "Note": {
    "dataSource": "couchbase",
    "public": true
  }
}

If i set ACL-datasource back to use the in-memory db everything works fine!? Do you have any clue whats going on?

**Comment by nolandubeau** [comment]
We are in the process of writing a fix for this as some of the functionality for WHERE clauses was not completed.

**Comment by nolandubeau** [comment]
Hi,  we have published a new version of the connector, which should fix this issue.  Please test and let us know.

**Comment by Andre197789xh** [comment]
Hi, thanks, thats great. Will test it tomorrow and give you feedback...
